# DO NOT EDIT THIS FILE!
#
# Python module IMCApp__POA generated by omniidl

import omniORB
omniORB.updateModule("IMCApp__POA")

# ** 1. Stub files contributing to this module
import IMC_idl

# ** 2. Sub-modules

# ** 3. End
