# Python stubs generated by omniidl from IMC.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "IMCApp"
#
__name__ = "IMCApp"
_0_IMCApp = omniORB.openModule("IMCApp", r"IMC.idl")
_0_IMCApp__POA = omniORB.openModule("IMCApp__POA", r"IMC.idl")


# interface CalcIMC
_0_IMCApp._d_CalcIMC = (omniORB.tcInternal.tv_objref, "IDL:IMCApp/CalcIMC:1.0", "CalcIMC")
omniORB.typeMapping["IDL:IMCApp/CalcIMC:1.0"] = _0_IMCApp._d_CalcIMC
_0_IMCApp.CalcIMC = omniORB.newEmptyClass()
class CalcIMC :
    _NP_RepositoryId = _0_IMCApp._d_CalcIMC[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_IMCApp.CalcIMC = CalcIMC
_0_IMCApp._tc_CalcIMC = omniORB.tcInternal.createTypeCode(_0_IMCApp._d_CalcIMC)
omniORB.registerType(CalcIMC._NP_RepositoryId, _0_IMCApp._d_CalcIMC, _0_IMCApp._tc_CalcIMC)

# CalcIMC operations and attributes
CalcIMC._d_imc = ((omniORB.tcInternal.tv_float, omniORB.tcInternal.tv_float), (omniORB.tcInternal.tv_float, ), None)

# CalcIMC object reference
class _objref_CalcIMC (CORBA.Object):
    _NP_RepositoryId = CalcIMC._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def imc(self, *args):
        return self._obj.invoke("imc", _0_IMCApp.CalcIMC._d_imc, args)

omniORB.registerObjref(CalcIMC._NP_RepositoryId, _objref_CalcIMC)
_0_IMCApp._objref_CalcIMC = _objref_CalcIMC
del CalcIMC, _objref_CalcIMC

# CalcIMC skeleton
__name__ = "IMCApp__POA"
class CalcIMC (PortableServer.Servant):
    _NP_RepositoryId = _0_IMCApp.CalcIMC._NP_RepositoryId


    _omni_op_d = {"imc": _0_IMCApp.CalcIMC._d_imc}

CalcIMC._omni_skeleton = CalcIMC
_0_IMCApp__POA.CalcIMC = CalcIMC
omniORB.registerSkeleton(CalcIMC._NP_RepositoryId, CalcIMC)
del CalcIMC
__name__ = "IMCApp"

#
# End of module "IMCApp"
#
__name__ = "IMC_idl"

_exported_modules = ( "IMCApp", )

# The end.
